#!/usr/bin/env python3
"""Convert the PNGs in assets/splash/ into src/splash_sprites.h.

White (lit) pixels are set, everything else is clear. Sprites are stored as
one 32-bit mask per column, bit 0 at the top, so they are at most 32 pixels
tall. Needs Pillow (pip install pillow)."""

import glob
import os
import re

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def const_name(file):
    base = os.path.splitext(os.path.basename(file))[0]
    return "SPRITE_" + re.sub(r"(?<=[a-z])(?=[A-Z0-9])", "_", base).upper()


def main():
    out = ["// Generated by tools/sprites.py from assets/splash/; do not edit.",
           "",
           "#pragma once",
           "",
           '#include "gfx.h"',
           ""]
    for path in sorted(glob.glob(os.path.join(ROOT, "assets", "splash", "*.png"))):
        im = Image.open(path).convert("LA")
        w, h = im.size
        if h > 32:
            raise SystemExit(f"{path}: sprites can be at most 32 pixels tall")
        px = im.load()
        cols = []
        for x in range(w):
            mask = 0
            for y in range(h):
                lum, alpha = px[x, y]
                if lum > 127 and alpha > 127:
                    mask |= 1 << y
            cols.append(mask)
        name = const_name(path)
        values = ", ".join(f"0x{c:08x}" for c in cols)
        out.append(f"static const uint32_t {name}_COLS[{w}] = {{ {values} }};")
        out.append(f"static const sprite_t {name} = {{ {w}, {h}, {name}_COLS }};")
        out.append("")

    path = os.path.join(ROOT, "src", "splash_sprites.h")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print(path)


if __name__ == "__main__":
    main()
