// Generated by tools/sprites.py from assets/diagram/; do not edit.

#pragma once

#include "gfx.h"

static const uint32_t SPRITE_BUTTON_DOWN_COLS[11] = { 0x000003ff, 0x00000201, 0x00000211, 0x00000231, 0x00000271, 0x000002fd, 0x00000271, 0x00000231, 0x00000211, 0x00000201, 0x000003ff };
static const sprite_t SPRITE_BUTTON_DOWN = { 11, 10, SPRITE_BUTTON_DOWN_COLS };

static const uint32_t SPRITE_BUTTON_UP_COLS[11] = { 0x000003ff, 0x00000201, 0x00000221, 0x00000231, 0x00000239, 0x000002fd, 0x00000239, 0x00000231, 0x00000221, 0x00000201, 0x000003ff };
static const sprite_t SPRITE_BUTTON_UP = { 11, 10, SPRITE_BUTTON_UP_COLS };

static const uint32_t SPRITE_CHORD_COLS[5] = { 0x00000888, 0x00001ddc, 0x00001ddc, 0x00000888, 0x00000fff };
static const sprite_t SPRITE_CHORD = { 5, 13, SPRITE_CHORD_COLS };

static const uint32_t SPRITE_GEAR_COLS[10] = { 0x00000030, 0x0000017a, 0x000000fc, 0x000001fe, 0x00000387, 0x00000387, 0x000001fe, 0x000000fc, 0x0000017a, 0x00000030 };
static const sprite_t SPRITE_GEAR = { 10, 10, SPRITE_GEAR_COLS };
